// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-FG0m6ZxMa4xHhWPBdoG32oMReYmqLaM',
    appId: '1:1041778256888:android:f59ca6f553432403aa440d',
    messagingSenderId: '1041778256888',
    projectId: 'neryfinancer',
    storageBucket: 'neryfinancer.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBH_4-2uBiCRXACZra-QZUNhw-3Cq-Q6k',
    appId: '1:1041778256888:web:88b7250c0a3dc742aa440d',
    messagingSenderId: '1041778256888',
    projectId: 'neryfinancer',
    authDomain: 'neryfinancer.firebaseapp.com',
    storageBucket: 'neryfinancer.firebasestorage.app',
    measurementId: 'G-ZKT037TB6N',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBH_4-2uBiCRXACZra-QZUNhw-3Cq-Q6k',
    appId: '1:1041778256888:web:88b7250c0a3dc742aa440d',
    messagingSenderId: '1041778256888',
    projectId: 'neryfinancer',
    authDomain: 'neryfinancer.firebaseapp.com',
    storageBucket: 'neryfinancer.firebasestorage.app',
    measurementId: 'G-ZKT037TB6N',
  );
}
